name: Run Tests (GH Inst.)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    permissions:
      contents: read
    strategy:
      matrix:
        api-level: [26, 30, 35]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          script: ./gradlew connectedAndroidTest
